from ..modelos import Role

ROLES_SUPERADMIN = (Role.SUPERADMIN,)
ROLES_ADMINISTRACION_INSTITUCIONAL = (
    Role.SUPERADMIN,
    Role.ADMIN_VICEMINISTERIO,
)
ROLES_ADMINISTRACION_CUENTAS = (Role.SUPERADMIN, Role.ADMIN)
ROLES_ADMINISTRACION_COMPLETA = (
    Role.SUPERADMIN,
    Role.ADMIN_VICEMINISTERIO,
    Role.ADMIN,
)
ROLES_RESPONSABLES_UNIDAD = (
    Role.PRODUCTIVE_UNIT_RESPONSIBLE,
    Role.EXPOSITOR,
)
ROLES_EXPOSITOR = (Role.EXPOSITOR,)
ROLES_GESTION_COMPARTIDA_LEGADA = (
    Role.SUPERADMIN,
    Role.ADMIN_VICEMINISTERIO,
    Role.EXPOSITOR,
)


def tiene_permiso(usuario, politica) -> bool:
    return bool(usuario and usuario.role in politica)
