import { expect,test,type Page } from "@playwright/test";

const users={admin:{id:"admin-1",username:"admin",email:"admin@gmail.com",first_name:"Ana",last_name:"Admin",role:"ADMIN",must_change_password:false},responsible:{id:"resp-1",username:"responsable",email:"responsable@gmail.com",first_name:"Eva",last_name:"Quispe",role:"PRODUCTIVE_UNIT_RESPONSIBLE",must_change_password:false}} as const;
const unit={id:"unidad-1",user_id:"resp-1",registration_request_id:"sol-1",nombre_comercial:"Manos Creativas",razon_social:"Manos Creativas SRL",nombre_representante:"Eva Quispe Mamani",nombres_representante:"Eva",apellido_paterno_representante:"Quispe",apellido_materno_representante:"Mamani",departamento:"La Paz",direccion_fisica:"Centro",telefono_whatsapp:"70000000",correo_electronico:"responsable@gmail.com",resena_comercial:"Artesanías",logo_url:null,estado:"ACTIVE",sectores:[]};
const dashboard={stats:{ferias:2,ferias_publicadas:1,productos:8,productos_disponibles:6,unidades_productivas:4,unidades_productivas_activas:3,solicitudes_pendientes:2,participaciones_pendientes:1,productos_sin_stock:0,solicitudes_ultimos_30_dias:0},proxima_feria:null,unidades_por_departamento:[],recent_audits:[{id:"audit-1",accion:"CREAR",entidad:"Feria",descripcion:"Feria creada",usuario:"admin",created_at:"2026-07-22T10:30:00-04:00"}]};
const adminUsers={items:[{id:"admin-2",username:"mlopez",email:"maria@gmail.com",first_name:"Maria",last_name:"Lopez",apellido_paterno:"Lopez",apellido_materno:"Quisbert",phone:"70000001",status:"ACTIVE",cargo:"Tecnica",unidad:"Viceministerio",observaciones:"",created_at:"2026-07-30T09:00:00-04:00",role:"ADMIN",must_change_password:false}],pagination:{page:1,per_page:10,pages:1,total:1,has_next:false,has_prev:false}} as const;
async function authenticated(page:Page,user:(typeof users)[keyof typeof users]){await page.addInitScript(session=>{localStorage.setItem("catalog_token","jwt-prueba");localStorage.setItem("catalog_refresh_token","refresh-prueba");localStorage.setItem("catalog_user",JSON.stringify(session));},user);await page.route("**/api/auth/me",route=>route.fulfill({json:user}));}

test("el administrador abre el portal canónico",async({page})=>{await authenticated(page,users.admin);await page.route("**/api/admin/dashboard",route=>route.fulfill({json:dashboard}));await page.goto("/admin");await expect(page.getByRole("heading",{name:"Resumen"})).toBeVisible();await expect(page.getByRole("link",{name:"Solicitudes",exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"Auditoría",exact:true})).toBeVisible();});
test("el administrador navega al modulo de administradores",async({page})=>{await authenticated(page,users.admin);await page.route("**/api/admin/users?**",route=>route.fulfill({json:adminUsers}));await page.goto("/admin/administradores");await expect(page.getByRole("heading",{name:"Administradores"})).toBeVisible();await expect(page.getByText("maria@gmail.com")).toBeVisible();await expect(page.getByRole("button",{name:"Nuevo administrador"})).toBeVisible();});
test("la auditoría muestra usuario fecha hora acción y descripción",async({page})=>{await authenticated(page,users.admin);await page.route("**/api/admin/audits?**",route=>route.fulfill({json:{items:dashboard.recent_audits,pagination:{page:1,per_page:20,pages:1,total:1,has_next:false,has_prev:false}}}));await page.goto("/admin/auditoria");await expect(page.getByRole("heading",{name:"Auditoría del sistema"})).toBeVisible();await expect(page.getByRole("columnheader",{name:"Usuario"})).toBeVisible();await expect(page.getByRole("columnheader",{name:"Fecha"})).toBeVisible();await expect(page.getByRole("columnheader",{name:"Hora"})).toBeVisible();await expect(page.getByText("Feria creada")).toBeVisible();});
test("el responsable no puede entrar al portal administrativo",async({page})=>{await authenticated(page,users.responsible);await page.route("**/api/productive-unit/products**",route=>route.fulfill({json:{items:[],pagination:{page:1,per_page:20,pages:0,total:0,has_next:false,has_prev:false}}}));await page.goto("/admin");await expect(page).toHaveURL(/\/unidad-productiva\/productos$/);await expect(page.getByRole("heading",{name:"Mis productos"})).toBeVisible();});
test("el responsable consulta y edita únicamente su Unidad Productiva",async({page})=>{await authenticated(page,users.responsible);await page.route("**/api/productive-unit/profile",route=>route.fulfill({json:unit}));await page.route("**/api/productive-sectors**",route=>route.fulfill({json:{items:[]}}));await page.goto("/unidad-productiva/perfil");await expect(page.getByRole("heading",{name:"Manos Creativas"})).toBeVisible();await expect(page.getByRole("link",{name:"Solicitudes"})).toHaveCount(0);await page.getByRole("button",{name:"Editar perfil"}).click();await expect(page.getByLabel("Nombre comercial")).toHaveValue("Manos Creativas");});
test("el responsable gestiona sus sectores productivos",async({page})=>{await authenticated(page,users.responsible);await page.route("**/api/productive-sectors**",route=>route.fulfill({json:{items:[{id:"sector-1",nombre:"Textiles",estado:"ACTIVE",es_otro:false}],pagination:{page:1,per_page:100,pages:1,total:1,has_next:false,has_prev:false}}}));await page.route("**/api/productive-unit/sectors",route=>route.fulfill({json:{sectores:[]}}));await page.goto("/unidad-productiva/sectores");await expect(page.getByRole("heading",{name:"Mis Sectores Productivos"})).toBeVisible();await page.getByLabel("Textiles").check();await expect(page.getByRole("button",{name:"Guardar sectores"})).toBeEnabled();});
test("el formulario de acceso redirige según el rol canónico",async({page})=>{await page.route("**/api/auth/login",route=>route.fulfill({json:{access_token:"jwt-login",refresh_token:"refresh-login",user:users.admin}}));await page.route("**/api/admin/dashboard",route=>route.fulfill({json:dashboard}));await page.goto("/login");await page.getByLabel("Usuario").fill("admin");await page.getByLabel("Contraseña",{exact:true}).fill("Temporal2026!");await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/admin$/);await expect(page.getByRole("heading",{name:"Resumen"})).toBeVisible();});
test("una contraseña temporal bloquea el resto del portal",async({page})=>{const temporary={...users.responsible,must_change_password:true};await page.route("**/api/auth/login",route=>route.fulfill({json:{access_token:"jwt-temporal",refresh_token:"refresh-temporal",user:temporary}}));await page.goto("/login");await page.getByLabel("Usuario").fill("responsable");await page.getByLabel("Contraseña",{exact:true}).fill("Temporal2026!");await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/cambiar-password$/);await expect(page.getByRole("heading",{name:"Cambie su contraseña"})).toBeVisible();});
