"""Esquema inicial"""
from alembic import op
import sqlalchemy as sa

revision='62cb1fe0782c'
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('exhibitor_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN_VICEMINISTERIO', 'EXPOSITOR', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='user_status'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.Column('unidad', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_accion'), 'audits', ['accion'], unique=False)
    op.create_index(op.f('ix_audits_created_at'), 'audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_audits_user_id'), 'audits', ['user_id'], unique=False)
    op.create_table('exhibitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('tipo_documento', sa.Enum('CI', 'NIT', 'OTRO', name='document_type'), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('nombre_responsable', sa.String(length=100), nullable=False),
    sa.Column('apellido_responsable', sa.String(length=100), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=11), nullable=False),
    sa.Column('email_gmail', sa.String(length=255), nullable=False),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descripcion_productos', sa.Text(), nullable=True),
    sa.Column('fotografia_perfil', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='exhibitor_status'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_gmail'),
    sa.UniqueConstraint('numero_documento'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_exhibitors_departamento'), 'exhibitors', ['departamento'], unique=False)
    op.create_index(op.f('ix_exhibitors_municipio'), 'exhibitors', ['municipio'], unique=False)
    op.create_index(op.f('ix_exhibitors_nombre_comercial'), 'exhibitors', ['nombre_comercial'], unique=False)
    op.create_table('fairs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('lugar', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('fecha_limite_registro', sa.Date(), nullable=True),
    sa.Column('imagen_portada', sa.String(length=500), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('DRAFT', 'PUBLISHED', 'DISABLED', 'FINISHED', name='fair_status'), nullable=False),
    sa.Column('visible_publicamente', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ck_fair_dates'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fairs_departamento'), 'fairs', ['departamento'], unique=False)
    op.create_index(op.f('ix_fairs_nombre'), 'fairs', ['nombre'], unique=False)
    op.create_index(op.f('ix_fairs_slug'), 'fairs', ['slug'], unique=True)
    op.create_table('password_recoveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_recoveries_user_id'), 'password_recoveries', ['user_id'], unique=False)
    op.create_table('exhibitor_type_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exhibitor_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['exhibitor_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exhibitor_id', 'type_id')
    )
    op.create_table('fair_exhibitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fair_id', sa.Uuid(), nullable=False),
    sa.Column('exhibitor_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('PENDING', 'AUTHORIZED', 'REJECTED', 'REVOKED', name='assignment_status'), nullable=False),
    sa.Column('numero_stand', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('authorized_by', sa.Uuid(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitors.id'], ),
    sa.ForeignKeyConstraint(['fair_id'], ['fairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fair_id', 'exhibitor_id', name='uq_fair_exhibitor')
    )
    op.create_table('fair_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fair_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fair_id'], ['fairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exhibitor_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('materiales_o_ingredientes', sa.Text(), nullable=True),
    sa.Column('lugar_origen', sa.String(length=150), nullable=True),
    sa.Column('presentacion', sa.String(length=150), nullable=True),
    sa.Column('informacion_adicional', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('AVAILABLE', 'OUT_OF_STOCK', 'INACTIVE', 'DELETED', name='product_status'), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exhibitor_id', 'slug')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_exhibitor_id'), 'products', ['exhibitor_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.drop_index(op.f('ix_products_exhibitor_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('fair_images')
    op.drop_table('fair_exhibitors')
    op.drop_table('exhibitor_type_links')
    op.drop_index(op.f('ix_password_recoveries_user_id'), table_name='password_recoveries')
    op.drop_table('password_recoveries')
    op.drop_index(op.f('ix_fairs_slug'), table_name='fairs')
    op.drop_index(op.f('ix_fairs_nombre'), table_name='fairs')
    op.drop_index(op.f('ix_fairs_departamento'), table_name='fairs')
    op.drop_table('fairs')
    op.drop_index(op.f('ix_exhibitors_nombre_comercial'), table_name='exhibitors')
    op.drop_index(op.f('ix_exhibitors_municipio'), table_name='exhibitors')
    op.drop_index(op.f('ix_exhibitors_departamento'), table_name='exhibitors')
    op.drop_table('exhibitors')
    op.drop_index(op.f('ix_audits_user_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_created_at'), table_name='audits')
    op.drop_index(op.f('ix_audits_accion'), table_name='audits')
    op.drop_table('audits')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('exhibitor_types')
    op.drop_table('categories')
    # ### end Alembic commands ###
