"""Agregar identificadores de Cloudinary

Revision ID: 8eb86b9491a1
Revises: dcdd5cb67e17
Create Date: 2026-07-30 11:40:43.340944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb86b9491a1'
down_revision = 'dcdd5cb67e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expositores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_logo_cloudinary', sa.String(length=500), nullable=True))

    with op.batch_alter_table('ferias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_portada_cloudinary', sa.String(length=500), nullable=True))

    with op.batch_alter_table('imagenes_feria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_cloudinary', sa.String(length=500), nullable=True))

    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_cloudinary', sa.String(length=500), nullable=True))

    with op.batch_alter_table('solicitudes_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_logo_cloudinary', sa.String(length=500), nullable=True))

    with op.batch_alter_table('unidades_productivas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_logo_cloudinary', sa.String(length=500), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_foto_cloudinary', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('identificador_foto_cloudinary')

    with op.batch_alter_table('unidades_productivas', schema=None) as batch_op:
        batch_op.drop_column('identificador_logo_cloudinary')

    with op.batch_alter_table('solicitudes_registro', schema=None) as batch_op:
        batch_op.drop_column('identificador_logo_cloudinary')

    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.drop_column('identificador_cloudinary')

    with op.batch_alter_table('imagenes_feria', schema=None) as batch_op:
        batch_op.drop_column('identificador_cloudinary')

    with op.batch_alter_table('expositores', schema=None) as batch_op:
        batch_op.drop_column('identificador_logo_cloudinary')

    with op.batch_alter_table('ferias', schema=None) as batch_op:
        batch_op.drop_column('identificador_portada_cloudinary')

    # ### end Alembic commands ###
