"""Esquema inicial limpio

Revision ID: dcdd5cb67e17
Revises: 
Create Date: 2026-07-30 09:06:03.764207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdd5cb67e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('identificador_url', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_categorias')),
    sa.UniqueConstraint('identificador_url', name=op.f('unico_categorias_identificador_url')),
    sa.UniqueConstraint('nombre', name=op.f('unico_categorias_nombre'))
    )
    op.create_table('codigos_acceso_revocados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identificador_codigo_acceso', sa.String(length=36), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_codigos_acceso_revocados'))
    )
    with op.batch_alter_table('codigos_acceso_revocados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_codigos_acceso_revocados_identificador_codigo_acceso'), ['identificador_codigo_acceso'], unique=True)

    op.create_table('estados_memoria_temporal',
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('clave', name=op.f('primaria_estados_memoria_temporal'))
    )
    op.create_table('sectores_productivos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', name='estado_sector_productivo'), nullable=False),
    sa.Column('es_otro', sa.Boolean(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_sectores_productivos')),
    sa.UniqueConstraint('nombre', name=op.f('unico_sectores_productivos_nombre'))
    )
    with op.batch_alter_table('sectores_productivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_sectores_productivos_estado'), ['estado'], unique=False)
        batch_op.create_index('indice_sectores_productivos_nombre', ['nombre'], unique=False)

    op.create_table('tipos_expositor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_tipos_expositor')),
    sa.UniqueConstraint('nombre', name=op.f('unico_tipos_expositor_nombre'))
    )
    op.create_table('unidades_administrativas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_unidades_administrativas')),
    sa.UniqueConstraint('nombre', name=op.f('unico_unidades_administrativas_nombre'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena_cifrada', sa.Text(), nullable=False),
    sa.Column('rol', sa.Enum('SUPERADMIN', 'ADMIN_VICEMINISTERIO', 'EXPOSITOR', 'ADMIN', 'PRODUCTIVE_UNIT_RESPONSIBLE', name='rol_usuario'), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'BLOCKED', name='estado_usuario'), nullable=False),
    sa.Column('debe_cambiar_contrasena', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos_acceso', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_sesion', sa.Integer(), nullable=False),
    sa.Column('fecha_ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cambio_contrasena', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_usuarios_correo'), ['correo'], unique=True)
        batch_op.create_index(batch_op.f('indice_usuarios_usuario'), ['usuario'], unique=True)

    op.create_table('auditorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.Column('direccion_ip', sa.String(length=45), nullable=True),
    sa.Column('agente_usuario', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('foranea_auditorias_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_auditorias'))
    )
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_auditorias_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('indice_auditorias_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('indice_auditorias_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('expositores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento', sa.Enum('CI', 'NIT', 'OTRO', name='tipo_documento'), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('nombre_responsable', sa.String(length=100), nullable=False),
    sa.Column('apellido_responsable', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno_responsable', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno_responsable', sa.String(length=100), nullable=True),
    sa.Column('celular_whatsapp', sa.String(length=11), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descripcion_productos', sa.Text(), nullable=True),
    sa.Column('nombre_tipo_expositor', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'BLOCKED', name='estado_expositor'), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('foranea_expositores_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_expositores')),
    sa.UniqueConstraint('correo', name=op.f('unico_expositores_correo')),
    sa.UniqueConstraint('numero_documento', name=op.f('unico_expositores_numero_documento')),
    sa.UniqueConstraint('usuario_id', name=op.f('unico_expositores_usuario_id'))
    )
    with op.batch_alter_table('expositores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_expositores_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('indice_expositores_municipio'), ['municipio'], unique=False)
        batch_op.create_index(batch_op.f('indice_expositores_nombre_comercial'), ['nombre_comercial'], unique=False)

    op.create_table('ferias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('identificador_url', sa.String(length=220), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('lugar', sa.String(length=200), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('fecha_limite_registro', sa.Date(), nullable=True),
    sa.Column('imagen_portada', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('DRAFT', 'PUBLISHED', 'DISABLED', 'FINISHED', name='estado_feria'), nullable=False),
    sa.Column('visible_publicamente', sa.Boolean(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_desactivacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name=op.f('verificacion_ferias_fechas_validas')),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], name=op.f('foranea_ferias_creado_por_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_ferias'))
    )
    with op.batch_alter_table('ferias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_ferias_departamento'), ['departamento'], unique=False)
        batch_op.create_index('indice_ferias_estado', ['estado'], unique=False)
        batch_op.create_index('indice_ferias_fecha_fin', ['fecha_fin'], unique=False)
        batch_op.create_index('indice_ferias_fecha_inicio', ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('indice_ferias_identificador_url'), ['identificador_url'], unique=True)
        batch_op.create_index(batch_op.f('indice_ferias_nombre'), ['nombre'], unique=False)

    op.create_table('perfiles_administradores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.Column('unidad', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('foranea_perfiles_administradores_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_perfiles_administradores')),
    sa.UniqueConstraint('numero_documento', name=op.f('unico_perfiles_administradores_numero_documento')),
    sa.UniqueConstraint('usuario_id', name=op.f('unico_perfiles_administradores_usuario_id'))
    )
    op.create_table('recuperaciones_contrasena',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_cifrado', sa.String(length=64), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('fecha_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('foranea_recuperaciones_contrasena_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_recuperaciones_contrasena')),
    sa.UniqueConstraint('codigo_cifrado', name=op.f('unico_recuperaciones_contrasena_codigo_cifrado'))
    )
    with op.batch_alter_table('recuperaciones_contrasena', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_recuperaciones_contrasena_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('solicitudes_registro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('registro_seprec', sa.String(length=100), nullable=True),
    sa.Column('registro_pro_bolivia', sa.String(length=100), nullable=True),
    sa.Column('nombres_representante', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno_representante', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno_representante', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('direccion_fisica', sa.String(length=255), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=30), nullable=False),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('tiktok_url', sa.String(length=500), nullable=True),
    sa.Column('resena_comercial', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='estado_solicitud_registro'), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('credentials_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_status', sa.Enum('PENDING', 'SENT', 'FAILED', name='estado_notificacion_solicitud'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['usuarios.id'], name=op.f('foranea_solicitudes_registro_reviewed_by_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_solicitudes_registro'))
    )
    with op.batch_alter_table('solicitudes_registro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_solicitudes_registro_correo_electronico'), ['correo_electronico'], unique=False)
        batch_op.create_index(batch_op.f('indice_solicitudes_registro_estado'), ['estado'], unique=False)
        batch_op.create_index('solicitud_pendiente_correo_unica', ['correo_electronico'], unique=True, postgresql_where=sa.text("estado = 'PENDING'"), sqlite_where=sa.text("estado = 'PENDING'"))
        batch_op.create_index('solicitud_pendiente_nit_unica', ['nit'], unique=True, postgresql_where=sa.text("estado = 'PENDING' AND nit IS NOT NULL"), sqlite_where=sa.text("estado = 'PENDING' AND nit IS NOT NULL"))

    op.create_table('expositores_feria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feria_id', sa.Uuid(), nullable=False),
    sa.Column('expositor_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('PENDING', 'AUTHORIZED', 'REJECTED', 'REVOKED', 'INACTIVE', name='estado_asignacion'), nullable=False),
    sa.Column('numero_stand', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('autorizado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_autorizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autorizado_por_usuario_id'], ['usuarios.id'], name=op.f('foranea_expositores_feria_autorizado_por_usuario_id_usuarios')),
    sa.ForeignKeyConstraint(['expositor_id'], ['expositores.id'], name=op.f('foranea_expositores_feria_expositor_id_expositores')),
    sa.ForeignKeyConstraint(['feria_id'], ['ferias.id'], name=op.f('foranea_expositores_feria_feria_id_ferias')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_expositores_feria')),
    sa.UniqueConstraint('feria_id', 'expositor_id', name='expositor_feria_unico')
    )
    op.create_table('imagenes_feria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feria_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('direccion_url', sa.String(length=500), nullable=False),
    sa.Column('texto_alternativo', sa.String(length=255), nullable=True),
    sa.Column('es_portada', sa.Boolean(), nullable=True),
    sa.Column('orden_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feria_id'], ['ferias.id'], name=op.f('foranea_imagenes_feria_feria_id_ferias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_imagenes_feria'))
    )
    op.create_table('productos_solicitud_registro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_request_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('descripcion_tecnica', sa.Text(), nullable=False),
    sa.Column('precio_referencia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registration_request_id'], ['solicitudes_registro.id'], name=op.f('foranea_productos_solicitud_registro_registration_request_id_solicitudes_registro'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_productos_solicitud_registro')),
    sa.UniqueConstraint('registration_request_id', 'orden', name='producto_solicitud_registro_orden_unico')
    )
    with op.batch_alter_table('productos_solicitud_registro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_productos_solicitud_registro_registration_request_id'), ['registration_request_id'], unique=False)

    op.create_table('sectores_solicitud_registro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_request_id', sa.Uuid(), nullable=False),
    sa.Column('productive_sector_id', sa.Uuid(), nullable=False),
    sa.Column('detalle_otro', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['productive_sector_id'], ['sectores_productivos.id'], name=op.f('foranea_sectores_solicitud_registro_productive_sector_id_sectores_productivos')),
    sa.ForeignKeyConstraint(['registration_request_id'], ['solicitudes_registro.id'], name=op.f('foranea_sectores_solicitud_registro_registration_request_id_solicitudes_registro'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_sectores_solicitud_registro')),
    sa.UniqueConstraint('registration_request_id', 'productive_sector_id', name='sector_solicitud_registro_unico')
    )
    op.create_table('tipos_expositor_asignados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expositor_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_expositor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['expositor_id'], ['expositores.id'], name=op.f('foranea_tipos_expositor_asignados_expositor_id_expositores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_expositor_id'], ['tipos_expositor.id'], name=op.f('foranea_tipos_expositor_asignados_tipo_expositor_id_tipos_expositor')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_tipos_expositor_asignados')),
    sa.UniqueConstraint('expositor_id', 'tipo_expositor_id', name='tipo_expositor_asignado_unico')
    )
    op.create_table('unidades_productivas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('registration_request_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('registro_seprec', sa.String(length=100), nullable=True),
    sa.Column('registro_pro_bolivia', sa.String(length=100), nullable=True),
    sa.Column('nombres_representante', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno_representante', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno_representante', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('direccion_fisica', sa.String(length=255), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=30), nullable=False),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('tiktok_url', sa.String(length=500), nullable=True),
    sa.Column('resena_comercial', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='estado_unidad_productiva'), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registration_request_id'], ['solicitudes_registro.id'], name=op.f('foranea_unidades_productivas_registration_request_id_solicitudes_registro')),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('foranea_unidades_productivas_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_unidades_productivas')),
    sa.UniqueConstraint('correo_electronico', name=op.f('unico_unidades_productivas_correo_electronico')),
    sa.UniqueConstraint('nit', name=op.f('unico_unidades_productivas_nit')),
    sa.UniqueConstraint('registration_request_id', name=op.f('unico_unidades_productivas_registration_request_id')),
    sa.UniqueConstraint('user_id', name=op.f('unico_unidades_productivas_user_id'))
    )
    with op.batch_alter_table('unidades_productivas', schema=None) as batch_op:
        batch_op.create_index('indice_unidades_productivas_correo_electronico', ['correo_electronico'], unique=False)
        batch_op.create_index(batch_op.f('indice_unidades_productivas_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('indice_unidades_productivas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('indice_unidades_productivas_nombre_comercial'), ['nombre_comercial'], unique=False)

    op.create_table('participaciones_feria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fair_id', sa.Uuid(), nullable=False),
    sa.Column('productive_unit_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('PENDING', 'AUTHORIZED', 'REJECTED', 'REVOKED', 'INACTIVE', name='estado_participacion_feria'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('authorized_by', sa.Uuid(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['usuarios.id'], name=op.f('foranea_participaciones_feria_authorized_by_usuarios')),
    sa.ForeignKeyConstraint(['fair_id'], ['ferias.id'], name=op.f('foranea_participaciones_feria_fair_id_ferias')),
    sa.ForeignKeyConstraint(['productive_unit_id'], ['unidades_productivas.id'], name=op.f('foranea_participaciones_feria_productive_unit_id_unidades_productivas')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_participaciones_feria')),
    sa.UniqueConstraint('fair_id', 'productive_unit_id', name='participacion_feria_unica')
    )
    with op.batch_alter_table('participaciones_feria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_participaciones_feria_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('indice_participaciones_feria_fair_id'), ['fair_id'], unique=False)
        batch_op.create_index(batch_op.f('indice_participaciones_feria_productive_unit_id'), ['productive_unit_id'], unique=False)

    op.create_table('productos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expositor_id', sa.Uuid(), nullable=True),
    sa.Column('unidad_productiva_id', sa.Uuid(), nullable=True),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('identificador_url', sa.String(length=220), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('materiales_o_ingredientes', sa.Text(), nullable=True),
    sa.Column('lugar_origen', sa.String(length=150), nullable=True),
    sa.Column('presentacion', sa.String(length=150), nullable=True),
    sa.Column('informacion_adicional', sa.Text(), nullable=True),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('descripcion_tecnica', sa.Text(), nullable=True),
    sa.Column('materia_prima', sa.Text(), nullable=True),
    sa.Column('dimensiones', sa.String(length=255), nullable=True),
    sa.Column('colores_disponibles', sa.String(length=255), nullable=True),
    sa.Column('certificaciones', sa.Text(), nullable=True),
    sa.Column('presentacion_empaque', sa.String(length=255), nullable=True),
    sa.Column('precio_referencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacidad_produccion_stock', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('DRAFT', 'AVAILABLE', 'OUT_OF_STOCK', 'RETIRED', 'INACTIVE', 'DELETED', name='estado_producto'), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('foranea_productos_categoria_id_categorias')),
    sa.ForeignKeyConstraint(['expositor_id'], ['expositores.id'], name=op.f('foranea_productos_expositor_id_expositores')),
    sa.ForeignKeyConstraint(['unidad_productiva_id'], ['unidades_productivas.id'], name=op.f('foranea_productos_unidad_productiva_id_unidades_productivas')),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_productos')),
    sa.UniqueConstraint('expositor_id', 'identificador_url', name='producto_expositor_url_unico')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('indice_productos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index('indice_productos_estado', ['estado'], unique=False)
        batch_op.create_index(batch_op.f('indice_productos_expositor_id'), ['expositor_id'], unique=False)
        batch_op.create_index(batch_op.f('indice_productos_unidad_productiva_id'), ['unidad_productiva_id'], unique=False)

    op.create_table('sectores_unidad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('productive_unit_id', sa.Uuid(), nullable=False),
    sa.Column('productive_sector_id', sa.Uuid(), nullable=False),
    sa.Column('detalle_otro', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', name='estado_sector_unidad'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('detalle_otro IS NULL OR length(trim(detalle_otro)) > 0', name=op.f('verificacion_sectores_unidad_detalle_otro_no_vacio')),
    sa.ForeignKeyConstraint(['productive_sector_id'], ['sectores_productivos.id'], name=op.f('foranea_sectores_unidad_productive_sector_id_sectores_productivos')),
    sa.ForeignKeyConstraint(['productive_unit_id'], ['unidades_productivas.id'], name=op.f('foranea_sectores_unidad_productive_unit_id_unidades_productivas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_sectores_unidad')),
    sa.UniqueConstraint('productive_unit_id', 'productive_sector_id', name='sector_unidad_unico')
    )
    op.create_table('imagenes_producto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('direccion_url', sa.String(length=500), nullable=False),
    sa.Column('texto_alternativo', sa.String(length=255), nullable=True),
    sa.Column('es_portada', sa.Boolean(), nullable=False),
    sa.Column('orden_visualizacion', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('foranea_imagenes_producto_producto_id_productos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('primaria_imagenes_producto')),
    sa.UniqueConstraint('producto_id', 'orden_visualizacion', name='imagen_producto_orden_unico')
    )
    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.create_index('imagen_producto_portada_unica', ['producto_id'], unique=True, postgresql_where=sa.text('es_portada IS TRUE'), sqlite_where=sa.text('es_portada IS 1'))
        batch_op.create_index('indice_imagenes_producto_producto_id', ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.drop_index('indice_imagenes_producto_producto_id')
        batch_op.drop_index('imagen_producto_portada_unica', postgresql_where=sa.text('es_portada IS TRUE'), sqlite_where=sa.text('es_portada IS 1'))

    op.drop_table('imagenes_producto')
    op.drop_table('sectores_unidad')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_productos_unidad_productiva_id'))
        batch_op.drop_index(batch_op.f('indice_productos_expositor_id'))
        batch_op.drop_index('indice_productos_estado')
        batch_op.drop_index(batch_op.f('indice_productos_categoria_id'))

    op.drop_table('productos')
    with op.batch_alter_table('participaciones_feria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_participaciones_feria_productive_unit_id'))
        batch_op.drop_index(batch_op.f('indice_participaciones_feria_fair_id'))
        batch_op.drop_index(batch_op.f('indice_participaciones_feria_estado'))

    op.drop_table('participaciones_feria')
    with op.batch_alter_table('unidades_productivas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_unidades_productivas_nombre_comercial'))
        batch_op.drop_index(batch_op.f('indice_unidades_productivas_estado'))
        batch_op.drop_index(batch_op.f('indice_unidades_productivas_departamento'))
        batch_op.drop_index('indice_unidades_productivas_correo_electronico')

    op.drop_table('unidades_productivas')
    op.drop_table('tipos_expositor_asignados')
    op.drop_table('sectores_solicitud_registro')
    with op.batch_alter_table('productos_solicitud_registro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_productos_solicitud_registro_registration_request_id'))

    op.drop_table('productos_solicitud_registro')
    op.drop_table('imagenes_feria')
    op.drop_table('expositores_feria')
    with op.batch_alter_table('solicitudes_registro', schema=None) as batch_op:
        batch_op.drop_index('solicitud_pendiente_nit_unica', postgresql_where=sa.text("estado = 'PENDING' AND nit IS NOT NULL"), sqlite_where=sa.text("estado = 'PENDING' AND nit IS NOT NULL"))
        batch_op.drop_index('solicitud_pendiente_correo_unica', postgresql_where=sa.text("estado = 'PENDING'"), sqlite_where=sa.text("estado = 'PENDING'"))
        batch_op.drop_index(batch_op.f('indice_solicitudes_registro_estado'))
        batch_op.drop_index(batch_op.f('indice_solicitudes_registro_correo_electronico'))

    op.drop_table('solicitudes_registro')
    with op.batch_alter_table('recuperaciones_contrasena', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_recuperaciones_contrasena_usuario_id'))

    op.drop_table('recuperaciones_contrasena')
    op.drop_table('perfiles_administradores')
    with op.batch_alter_table('ferias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_ferias_nombre'))
        batch_op.drop_index(batch_op.f('indice_ferias_identificador_url'))
        batch_op.drop_index('indice_ferias_fecha_inicio')
        batch_op.drop_index('indice_ferias_fecha_fin')
        batch_op.drop_index('indice_ferias_estado')
        batch_op.drop_index(batch_op.f('indice_ferias_departamento'))

    op.drop_table('ferias')
    with op.batch_alter_table('expositores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_expositores_nombre_comercial'))
        batch_op.drop_index(batch_op.f('indice_expositores_municipio'))
        batch_op.drop_index(batch_op.f('indice_expositores_departamento'))

    op.drop_table('expositores')
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_auditorias_usuario_id'))
        batch_op.drop_index(batch_op.f('indice_auditorias_fecha_creacion'))
        batch_op.drop_index(batch_op.f('indice_auditorias_accion'))

    op.drop_table('auditorias')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_usuarios_usuario'))
        batch_op.drop_index(batch_op.f('indice_usuarios_correo'))

    op.drop_table('usuarios')
    op.drop_table('unidades_administrativas')
    op.drop_table('tipos_expositor')
    with op.batch_alter_table('sectores_productivos', schema=None) as batch_op:
        batch_op.drop_index('indice_sectores_productivos_nombre')
        batch_op.drop_index(batch_op.f('indice_sectores_productivos_estado'))

    op.drop_table('sectores_productivos')
    op.drop_table('estados_memoria_temporal')
    with op.batch_alter_table('codigos_acceso_revocados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('indice_codigos_acceso_revocados_identificador_codigo_acceso'))

    op.drop_table('codigos_acceso_revocados')
    op.drop_table('categorias')
    # ### end Alembic commands ###
